
/**
 * This file is generated by Sencha Cmd and should NOT be edited.  It is 
 * provided to support globbing requires, custom xtypes, and other 
 * metadata-driven class system features 
 */
Ext.Loader.addClassPathMappings({
  "Ext.locale.zh_CN.view.AbstractView": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.toolbar.Paging": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.Component": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.Date": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.rtl.EventObjectImpl": "../../../ext/src/rtl/EventObject.js",
  "overrides.Table": "../../overrides/Table.js",
  "Zstlweb": "../../app",
  "Ext.locale.zh_CN.form.field.Text": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.VTypes": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.Base": "../../../ext/locale/ext-lang-zh_CN.js",
  "overrides.TabCloseMenu": "../../overrides/TabCloseMenu.js",
  "Ext.locale.zh_CN.grid.plugin.DragDrop": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext": "../../../ext/src",
  "Ext.locale.zh_CN.tab.Tab": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.grid.PropertyColumnModel": "../../../ext/locale/ext-lang-zh_CN.js",
  "Zstlweb.Application": "../../app/application.js",
  "overrides.BasicForm": "../../overrides/BasicForm.js",
  "overrides": "../../../packages/my-custom-theme/overrides",
  "Ext.locale.zh_CN.grid.header.Container": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.window.MessageBox": "../../../ext/locale/ext-lang-zh_CN.js",
  "overrides.RowExpander": "../../overrides/RowExpander.js",
  "Ext.locale.zh_CN.form.field.ComboBox": "../../../ext/locale/ext-lang-zh_CN.js",
  "Ext.locale.zh_CN.form.field.Number": "../../../ext/locale/ext-lang-zh_CN.js",
  "overrides.VType": "../../overrides/VType.js",
  "Ext.locale.zh_CN.view.View": "../../../ext/locale/ext-lang-zh_CN.js",
  "overrides.Date": "../../overrides/Date.js",
  "Ext.locale.zh_CN.picker.Month": "../../../ext/locale/ext-lang-zh_CN.js",
  " Ext.Msg": "../../../ext/src/window/MessageBox.js",
  "Ext.locale.zh_CN.picker.Date": "../../../ext/locale/ext-lang-zh_CN.js",
  "overrides.Format": "../../overrides/Format.js",
  "Ext.locale.zh_CN.form.field.HtmlEditor": "../../../ext/locale/ext-lang-zh_CN.js"
});
Ext.ClassManager.addNameAlternateMappings({
  "Ext.locale.zh_CN.toolbar.Paging": [],
  "overrides.grid.RowEditor": [],
  "Ext.locale.zh_CN.form.field.Date": [],
  "Zstlweb.controller.bbcx": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "Zstlweb.controller.Component": [],
  "overrides.layout.component.Dock": [],
  "Ext.locale.zh_CN.form.field.VTypes": [],
  "Zstlweb.store.component.Status": [],
  "Ext.ux.ajax.XmlSimlet": [],
  "Ext.ux.event.Driver": [],
  "Ext.ux.DataView.DragSelector": [],
  "Zstlweb.Application": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.locale.zh_CN.grid.header.Container": [],
  "Zstlweb.controller.jycx": [],
  "overrides.RowExpander": [],
  "Ext.locale.zh_CN.window.MessageBox": [],
  "Ext.locale.zh_CN.form.field.Number": [],
  "Ext.ux.form.MultiSelect": [
    "Ext.ux.Multiselect"
  ],
  "Ext.locale.zh_CN.view.View": [],
  "Zstlweb.view.role.Add": [],
  "Zstlweb.view.role.List": [],
  "Zstlweb.view.component.Status": [],
  "Ext.locale.zh_CN.picker.Month": [],
  "Ext.ux.PreviewPlugin": [],
  "Zstlweb.view.zhgl.zhcx": [],
  "overrides.toolbar.Paging": [],
  "Zstlweb.view.user.List": [],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [],
  "Zstlweb.view.zhgl.zhlscx": [],
  "Ext.locale.zh_CN.form.field.HtmlEditor": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [],
  "Ext.locale.zh_CN.view.AbstractView": [],
  "Ext.ux.ajax.Simlet": [],
  "Ext.ux.SlidingPager": [],
  "Ext.locale.zh_CN.Component": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [],
  "overrides.resizer.Splitter": [],
  "Ext.locale.zh_CN.form.field.Text": [],
  "Ext.ux.event.Recorder": [],
  "Zstlweb.view.Viewport": [],
  "Zstlweb.controller.Users": [],
  "overrides.Component": [],
  "overrides.TabCloseMenu": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [],
  "Ext.ux.TabScrollerMenu": [],
  "Ext.ux.IFrame": [],
  "overrides.Date": [],
  "Ext.ux.form.SearchField": [],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Zstlweb.view.South": [],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [],
  "Ext.ux.TreePicker": [],
  "overrides.Format": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "Ext.data.PagingMemoryProxy"
  ],
  "overrides.toolbar.Toolbar": [],
  "Zstlweb.view.user.Add": [],
  "Zstlweb.controller.Roles": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Zstlweb.controller.zhgl": [],
  "Ext.ux.GroupTabRenderer": [],
  "Zstlweb.view.login.LoginForm": [],
  "overrides.form.field.HtmlEditor": [],
  "Zstlweb.controller.Routes": [],
  "Zstlweb.view.bbcx.shck": [],
  "Ext.ux.FieldReplicator": [],
  "Zstlweb.view.West": [],
  "overrides.grid.column.RowNumberer": [],
  "Ext.locale.zh_CN.form.field.Base": [],
  "Ext.ux.grid.filter.ListFilter": [],
  "Ext.locale.zh_CN.grid.plugin.DragDrop": [],
  "Zstlweb.view.jycx.ssjycx": [],
  "Zstlweb.view.component.DateTime": [],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "overrides.panel.Table": [],
  "Zstlweb.view.bbcx.frmxdetail": [],
  "overrides.BasicForm": [],
  "Ext.ux.GMapPanel": [],
  "Zstlweb.view.component.UTypes": [],
  "Ext.ux.GroupTabPanel": [],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [],
  "Zstlweb.view.user.Edit": [],
  "Ext.ux.statusbar.ValidationStatus": [],
  "overrides.panel.Panel": [],
  "Ext.ux.layout.Center": [],
  "Zstlweb.view.component.picker.DateTimePicker": [
    "Ext.DateTimePicker"
  ],
  "Ext.ux.DataView.Animated": [],
  "Zstlweb.view.component.Routes": [],
  "Zstlweb.view.login.PasswordReset": [],
  "Zstlweb.controller.Index": [],
  "Ext.ux.statusbar.StatusBar": [
    "Ext.ux.StatusBar"
  ],
  "Zstlweb.view.bbcx.frmx": [],
  "Zstlweb.view.role.Edit": [],
  "overrides.container.ButtonGroup": [],
  "overrides.panel.Tool": [],
  "overrides.Table": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Zstlweb.view.bbcx.shdz": [],
  "Ext.ux.event.Player": [],
  "Zstlweb.controller.Login": [],
  "Zstlweb.store.component.Routes": [],
  "Zstlweb.view.login.Logout": [],
  "overrides.menu.Menu": [],
  "Ext.locale.zh_CN.tab.Tab": [],
  "Zstlweb.view.Center": [],
  "Ext.locale.zh_CN.grid.PropertyColumnModel": [],
  "Ext.ux.ToolbarDroppable": [],
  "Zstlweb.view.North": [],
  "Ext.ux.event.Maker": [],
  "overrides.menu.Separator": [],
  "Ext.ux.DataView.Draggable": [],
  "overrides.picker.Month": [],
  "Ext.locale.zh_CN.form.field.ComboBox": [],
  "overrides.VType": [],
  "Ext.ux.TabCloseMenu": [],
  "Ext.ux.DataTip": [],
  "Ext.ux.grid.filter.DateTimeFilter": [],
  "Ext.ux.form.ItemSelector": [
    "Ext.ux.ItemSelector"
  ],
  "Ext.ux.ajax.JsonSimlet": [],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [],
  "overrides.tab.Tab": [],
  "Ext.locale.zh_CN.picker.Date": []
});
Ext.ClassManager.addNameAliasMappings({
  "Ext.locale.zh_CN.toolbar.Paging": [],
  "overrides.grid.RowEditor": [],
  "Ext.locale.zh_CN.form.field.Date": [],
  "Zstlweb.controller.bbcx": [],
  "Ext.ux.ajax.DataSimlet": [],
  "Ext.ux.grid.TransformGrid": [],
  "Zstlweb.controller.Component": [],
  "overrides.layout.component.Dock": [],
  "Ext.locale.zh_CN.form.field.VTypes": [],
  "Zstlweb.store.component.Status": [],
  "Ext.ux.ajax.XmlSimlet": [
    "simlet.xml"
  ],
  "Ext.ux.event.Driver": [],
  "Ext.ux.DataView.DragSelector": [],
  "Zstlweb.Application": [],
  "Ext.ux.grid.menu.ListMenu": [],
  "Ext.locale.zh_CN.grid.header.Container": [],
  "Zstlweb.controller.jycx": [],
  "overrides.RowExpander": [],
  "Ext.locale.zh_CN.window.MessageBox": [],
  "Ext.locale.zh_CN.form.field.Number": [],
  "Ext.ux.form.MultiSelect": [
    "widget.multiselect",
    "widget.multiselectfield"
  ],
  "Ext.locale.zh_CN.view.View": [],
  "Zstlweb.view.role.Add": [
    "widget.roleadd"
  ],
  "Zstlweb.view.role.List": [
    "widget.rolelist"
  ],
  "Zstlweb.view.component.Status": [
    "widget.status"
  ],
  "Ext.locale.zh_CN.picker.Month": [],
  "Ext.ux.PreviewPlugin": [
    "plugin.preview"
  ],
  "Zstlweb.view.zhgl.zhcx": [
    "widget.zhglzhcx"
  ],
  "overrides.toolbar.Paging": [],
  "Zstlweb.view.user.List": [
    "widget.userlist"
  ],
  "Ext.ux.ajax.SimXhr": [],
  "Ext.ux.event.RecorderManager": [
    "widget.eventrecordermanager"
  ],
  "Zstlweb.view.zhgl.zhlscx": [
    "widget.zhglzhlscx"
  ],
  "Ext.locale.zh_CN.form.field.HtmlEditor": [],
  "Ext.ux.ProgressBarPager": [],
  "Ext.ux.CellDragDrop": [
    "plugin.celldragdrop"
  ],
  "Ext.locale.zh_CN.view.AbstractView": [],
  "Ext.ux.ajax.Simlet": [
    "simlet.basic"
  ],
  "Ext.ux.SlidingPager": [],
  "Ext.locale.zh_CN.Component": [],
  "Ext.ux.TabReorderer": [],
  "Ext.ux.grid.filter.NumericFilter": [
    "gridfilter.numeric"
  ],
  "overrides.resizer.Splitter": [],
  "Ext.locale.zh_CN.form.field.Text": [],
  "Ext.ux.event.Recorder": [],
  "Zstlweb.view.Viewport": [],
  "Zstlweb.controller.Users": [],
  "overrides.Component": [],
  "overrides.TabCloseMenu": [],
  "Ext.ux.ajax.SimManager": [],
  "Ext.ux.grid.filter.BooleanFilter": [
    "gridfilter.boolean"
  ],
  "Ext.ux.TabScrollerMenu": [
    "plugin.tabscrollermenu"
  ],
  "Ext.ux.IFrame": [
    "widget.uxiframe"
  ],
  "overrides.Date": [],
  "Ext.ux.form.SearchField": [
    "widget.searchfield"
  ],
  "Ext.ux.dd.CellFieldDropZone": [],
  "Zstlweb.view.South": [
    "widget.south"
  ],
  "Ext.ux.LiveSearchGridPanel": [],
  "Ext.ux.grid.filter.DateFilter": [
    "gridfilter.date"
  ],
  "Ext.ux.TreePicker": [
    "widget.treepicker"
  ],
  "overrides.Format": [],
  "Ext.ux.data.PagingMemoryProxy": [
    "proxy.pagingmemory"
  ],
  "overrides.toolbar.Toolbar": [],
  "Zstlweb.view.user.Add": [
    "widget.useradd"
  ],
  "Zstlweb.controller.Roles": [],
  "Ext.ux.BoxReorderer": [],
  "Ext.ux.grid.filter.Filter": [],
  "Zstlweb.controller.zhgl": [],
  "Ext.ux.GroupTabRenderer": [
    "plugin.grouptabrenderer"
  ],
  "Zstlweb.view.login.LoginForm": [
    "widget.loginform"
  ],
  "overrides.form.field.HtmlEditor": [],
  "Zstlweb.controller.Routes": [],
  "Zstlweb.view.bbcx.shck": [
    "widget.bbcxshck"
  ],
  "Ext.ux.FieldReplicator": [],
  "Zstlweb.view.West": [
    "widget.west"
  ],
  "overrides.grid.column.RowNumberer": [],
  "Ext.locale.zh_CN.form.field.Base": [],
  "Ext.ux.grid.filter.ListFilter": [
    "gridfilter.list"
  ],
  "Ext.locale.zh_CN.grid.plugin.DragDrop": [],
  "Zstlweb.view.jycx.ssjycx": [
    "widget.jycxssjycx"
  ],
  "Zstlweb.view.component.DateTime": [
    "widget.datetimefield"
  ],
  "Ext.ux.dd.PanelFieldDragZone": [],
  "overrides.panel.Table": [],
  "Zstlweb.view.bbcx.frmxdetail": [
    "widget.bbcxfrmxdetail"
  ],
  "overrides.BasicForm": [],
  "Ext.ux.GMapPanel": [
    "widget.gmappanel"
  ],
  "Zstlweb.view.component.UTypes": [
    "widget.uitypes"
  ],
  "Ext.ux.GroupTabPanel": [
    "widget.grouptabpanel"
  ],
  "Ext.ux.DataView.LabelEditor": [],
  "Ext.ux.grid.filter.StringFilter": [
    "gridfilter.string"
  ],
  "Zstlweb.view.user.Edit": [
    "widget.useredit"
  ],
  "Ext.ux.statusbar.ValidationStatus": [],
  "overrides.panel.Panel": [],
  "Ext.ux.layout.Center": [
    "layout.ux.center"
  ],
  "Zstlweb.view.component.picker.DateTimePicker": [
    "widget.datetimepicker"
  ],
  "Ext.ux.DataView.Animated": [],
  "Zstlweb.view.component.Routes": [
    "widget.routes"
  ],
  "Zstlweb.view.login.PasswordReset": [
    "widget.passwordreset"
  ],
  "Zstlweb.controller.Index": [],
  "Ext.ux.statusbar.StatusBar": [
    "widget.statusbar"
  ],
  "Zstlweb.view.bbcx.frmx": [
    "widget.bbcxfrmx"
  ],
  "Zstlweb.view.role.Edit": [
    "widget.roledit"
  ],
  "overrides.container.ButtonGroup": [],
  "overrides.panel.Tool": [],
  "overrides.Table": [],
  "Ext.ux.grid.menu.RangeMenu": [],
  "Ext.ux.RowExpander": [],
  "Zstlweb.view.bbcx.shdz": [
    "widget.bbcxshdz"
  ],
  "Ext.ux.event.Player": [],
  "Zstlweb.controller.Login": [],
  "Zstlweb.store.component.Routes": [],
  "Zstlweb.view.login.Logout": [
    "widget.logout"
  ],
  "overrides.menu.Menu": [],
  "Ext.locale.zh_CN.tab.Tab": [],
  "Zstlweb.view.Center": [
    "widget.center"
  ],
  "Ext.locale.zh_CN.grid.PropertyColumnModel": [],
  "Ext.ux.ToolbarDroppable": [],
  "Zstlweb.view.North": [
    "widget.north"
  ],
  "Ext.ux.event.Maker": [],
  "overrides.menu.Separator": [],
  "Ext.ux.DataView.Draggable": [],
  "overrides.picker.Month": [],
  "Ext.locale.zh_CN.form.field.ComboBox": [],
  "overrides.VType": [],
  "Ext.ux.TabCloseMenu": [
    "plugin.tabclosemenu"
  ],
  "Ext.ux.DataTip": [
    "plugin.datatip"
  ],
  "Ext.ux.grid.filter.DateTimeFilter": [
    "gridfilter.datetime"
  ],
  "Ext.ux.form.ItemSelector": [
    "widget.itemselector",
    "widget.itemselectorfield"
  ],
  "Ext.ux.ajax.JsonSimlet": [
    "simlet.json"
  ],
  "Ext.ux.Spotlight": [],
  "Ext.ux.grid.FiltersFeature": [
    "feature.filters"
  ],
  "overrides.tab.Tab": [],
  "Ext.locale.zh_CN.picker.Date": []
});
Ext.Loader.loadScript("../../../packages/my-custom-theme/overrides/Component.js");
Ext.Loader.loadScript("../../../packages/my-custom-theme/overrides/panel/Panel.js");
Ext.Loader.loadScript("../../../packages/my-custom-theme/overrides/layout/component/Dock.js");
Ext.Loader.loadScript("../../../packages/my-custom-theme/overrides/toolbar/Toolbar.js");
Ext.Loader.loadScript("../../../packages/my-custom-theme/overrides/container/ButtonGroup.js");
Ext.Loader.loadScript("../../../packages/my-custom-theme/overrides/toolbar/Paging.js");
Ext.Loader.loadScript("../../../packages/my-custom-theme/overrides/picker/Month.js");
Ext.Loader.loadScript("../../../packages/my-custom-theme/overrides/form/field/HtmlEditor.js");
Ext.Loader.loadScript("../../../packages/my-custom-theme/overrides/panel/Table.js");
Ext.Loader.loadScript("../../../packages/my-custom-theme/overrides/grid/RowEditor.js");
Ext.Loader.loadScript("../../../packages/my-custom-theme/overrides/grid/column/RowNumberer.js");
Ext.Loader.loadScript("../../../packages/my-custom-theme/overrides/resizer/Splitter.js");
Ext.Loader.loadScript("../../../packages/my-custom-theme/overrides/menu/Menu.js");
Ext.Loader.loadScript("../../../packages/my-custom-theme/overrides/menu/Separator.js");
Ext.Loader.loadScript("../../../packages/my-custom-theme/overrides/panel/Tool.js");
Ext.Loader.loadScript("../../../packages/my-custom-theme/overrides/tab/Tab.js");
